require('dotenv').config();
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');

const libraryUserId = new mongoose.Types.ObjectId('69f34161021f05ae63bc3b82');

const recipes = [
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Greek Yogurt Parfait',
    description: 'Creamy yogurt layered with granola and fresh berries.',
    category: 'Breakfast',
    cuisine: 'American',
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    servings: 1,
    prepTime: 5,
    cookTime: 0,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800',
    ingredients: [
      { name: 'Greek yogurt', quantity: 200, unit: 'grams', calories: 130, protein: 17, carbs: 9, fat: 0 },
      { name: 'Granola', quantity: 50, unit: 'grams', calories: 120, protein: 3, carbs: 22, fat: 3 },
      { name: 'Mixed berries', quantity: 100, unit: 'grams', calories: 50, protein: 1, carbs: 12, fat: 0 },
      { name: 'Honey', quantity: 1, unit: 'tbsp', calories: 60, protein: 0, carbs: 17, fat: 0 },
    ],
    steps: ['Spoon yogurt into a glass or bowl.', 'Layer with granola and berries.', 'Drizzle honey on top and serve.'],
    totalNutrition: { calories: 360, protein: 21, carbs: 60, fat: 3 },
    perServing: { calories: 360, protein: 21, carbs: 60, fat: 3 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Spinach and Feta Omelette',
    description: 'Fluffy omelette packed with spinach and salty feta cheese.',
    category: 'Breakfast',
    cuisine: 'Mediterranean',
    dietaryTags: ['Vegetarian', 'Gluten-Free', 'Keto'],
    servings: 1,
    prepTime: 5,
    cookTime: 10,
    image: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800',
    ingredients: [
      { name: 'Eggs', quantity: 3, unit: 'whole', calories: 210, protein: 18, carbs: 1, fat: 15 },
      { name: 'Fresh spinach', quantity: 60, unit: 'grams', calories: 15, protein: 2, carbs: 2, fat: 0 },
      { name: 'Feta cheese', quantity: 40, unit: 'grams', calories: 100, protein: 5, carbs: 1, fat: 8 },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp', calories: 60, protein: 0, carbs: 0, fat: 7 },
    ],
    steps: ['Whisk eggs with salt and pepper.', 'Heat olive oil in a pan over medium heat.', 'Pour in eggs and add spinach and feta.', 'Fold omelette in half and serve hot.'],
    totalNutrition: { calories: 385, protein: 25, carbs: 4, fat: 30 },
    perServing: { calories: 385, protein: 25, carbs: 4, fat: 30 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Banana Protein Pancakes',
    description: 'Fluffy protein-packed pancakes made with banana and oats.',
    category: 'Breakfast',
    cuisine: 'American',
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    servings: 2,
    prepTime: 5,
    cookTime: 15,
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800',
    ingredients: [
      { name: 'Banana', quantity: 2, unit: 'whole', calories: 180, protein: 2, carbs: 46, fat: 0 },
      { name: 'Eggs', quantity: 2, unit: 'whole', calories: 140, protein: 12, carbs: 1, fat: 10 },
      { name: 'Rolled oats', quantity: 80, unit: 'grams', calories: 150, protein: 5, carbs: 27, fat: 3 },
      { name: 'Protein powder', quantity: 30, unit: 'grams', calories: 120, protein: 24, carbs: 3, fat: 1 },
    ],
    steps: ['Blend banana, eggs, oats and protein powder.', 'Heat a non-stick pan over medium heat.', 'Pour small rounds and cook 2 minutes each side.', 'Serve with fresh fruit and maple syrup.'],
    totalNutrition: { calories: 590, protein: 43, carbs: 77, fat: 14 },
    perServing: { calories: 295, protein: 22, carbs: 39, fat: 7 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Turkey and Avocado Wrap',
    description: 'Light and filling wrap with turkey, avocado and fresh veggies.',
    category: 'Lunch',
    cuisine: 'American',
    dietaryTags: ['Gluten-Free'],
    servings: 1,
    prepTime: 10,
    cookTime: 0,
    image: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800',
    ingredients: [
      { name: 'Whole wheat tortilla', quantity: 1, unit: 'whole', calories: 130, protein: 4, carbs: 24, fat: 3 },
      { name: 'Turkey breast', quantity: 100, unit: 'grams', calories: 110, protein: 24, carbs: 0, fat: 1 },
      { name: 'Avocado', quantity: 0.5, unit: 'whole', calories: 80, protein: 1, carbs: 4, fat: 7 },
      { name: 'Romaine lettuce', quantity: 50, unit: 'grams', calories: 10, protein: 1, carbs: 2, fat: 0 },
    ],
    steps: ['Lay tortilla flat on a surface.', 'Layer turkey, avocado and lettuce.', 'Season with salt, pepper and mustard.', 'Roll tightly and slice in half.'],
    totalNutrition: { calories: 330, protein: 30, carbs: 30, fat: 11 },
    perServing: { calories: 330, protein: 30, carbs: 30, fat: 11 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Lentil Soup',
    description: 'Hearty and warming red lentil soup with Middle Eastern spices.',
    category: 'Lunch',
    cuisine: 'Middle Eastern',
    dietaryTags: ['Vegan', 'Vegetarian', 'Gluten-Free'],
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
    ingredients: [
      { name: 'Red lentils', quantity: 300, unit: 'grams', calories: 340, protein: 24, carbs: 58, fat: 1 },
      { name: 'Onion', quantity: 1, unit: 'whole', calories: 40, protein: 1, carbs: 9, fat: 0 },
      { name: 'Cumin', quantity: 2, unit: 'tsp', calories: 15, protein: 1, carbs: 2, fat: 1 },
      { name: 'Vegetable broth', quantity: 1, unit: 'liter', calories: 20, protein: 1, carbs: 4, fat: 0 },
    ],
    steps: ['Saute onion with cumin until golden.', 'Add lentils and vegetable broth.', 'Simmer for 25 minutes until lentils are soft.', 'Blend half the soup and stir back in.'],
    totalNutrition: { calories: 415, protein: 27, carbs: 73, fat: 2 },
    perServing: { calories: 104, protein: 7, carbs: 18, fat: 1 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Tuna Nicoise Salad',
    description: 'Classic French salad with tuna, eggs, olives and green beans.',
    category: 'Lunch',
    cuisine: 'French',
    dietaryTags: ['Gluten-Free', 'Keto'],
    servings: 2,
    prepTime: 15,
    cookTime: 10,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
    ingredients: [
      { name: 'Canned tuna', quantity: 200, unit: 'grams', calories: 180, protein: 40, carbs: 0, fat: 2 },
      { name: 'Eggs', quantity: 2, unit: 'whole', calories: 140, protein: 12, carbs: 1, fat: 10 },
      { name: 'Green beans', quantity: 150, unit: 'grams', calories: 35, protein: 2, carbs: 7, fat: 0 },
      { name: 'Olives', quantity: 60, unit: 'grams', calories: 80, protein: 1, carbs: 4, fat: 7 },
    ],
    steps: ['Boil eggs for 8 minutes then cool and peel.', 'Blanch green beans for 3 minutes.', 'Arrange lettuce, tuna, eggs, beans and olives.', 'Drizzle with olive oil and lemon dressing.'],
    totalNutrition: { calories: 435, protein: 55, carbs: 12, fat: 19 },
    perServing: { calories: 218, protein: 28, carbs: 6, fat: 10 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Mushroom Risotto',
    description: 'Creamy Italian risotto with mixed mushrooms and parmesan.',
    category: 'Dinner',
    cuisine: 'Italian',
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    servings: 2,
    prepTime: 10,
    cookTime: 30,
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800',
    ingredients: [
      { name: 'Arborio rice', quantity: 200, unit: 'grams', calories: 280, protein: 5, carbs: 62, fat: 1 },
      { name: 'Mixed mushrooms', quantity: 200, unit: 'grams', calories: 40, protein: 4, carbs: 6, fat: 0 },
      { name: 'Parmesan', quantity: 50, unit: 'grams', calories: 130, protein: 11, carbs: 1, fat: 9 },
      { name: 'Vegetable broth', quantity: 700, unit: 'ml', calories: 15, protein: 1, carbs: 3, fat: 0 },
    ],
    steps: ['Saute mushrooms in butter until golden.', 'Toast arborio rice for 2 minutes.', 'Add broth ladle by ladle stirring constantly.', 'Finish with parmesan and butter.'],
    totalNutrition: { calories: 465, protein: 21, carbs: 72, fat: 10 },
    perServing: { calories: 233, protein: 11, carbs: 36, fat: 5 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Baked Chicken Thighs',
    description: 'Juicy oven-baked chicken thighs with garlic and herbs.',
    category: 'Dinner',
    cuisine: 'American',
    dietaryTags: ['Gluten-Free', 'Keto'],
    servings: 4,
    prepTime: 10,
    cookTime: 35,
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c4?w=800',
    ingredients: [
      { name: 'Chicken thighs', quantity: 600, unit: 'grams', calories: 720, protein: 72, carbs: 0, fat: 48 },
      { name: 'Garlic', quantity: 4, unit: 'cloves', calories: 20, protein: 1, carbs: 4, fat: 0 },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp', calories: 120, protein: 0, carbs: 0, fat: 14 },
      { name: 'Rosemary', quantity: 2, unit: 'tsp', calories: 5, protein: 0, carbs: 1, fat: 0 },
    ],
    steps: ['Preheat oven to 200C.', 'Rub chicken with garlic, olive oil and rosemary.', 'Place in baking dish skin side up.', 'Bake for 35 minutes until golden and cooked through.'],
    totalNutrition: { calories: 865, protein: 73, carbs: 5, fat: 62 },
    perServing: { calories: 216, protein: 18, carbs: 1, fat: 16 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Shrimp Tacos',
    description: 'Zesty shrimp tacos with cabbage slaw and lime crema.',
    category: 'Dinner',
    cuisine: 'Mexican',
    dietaryTags: ['Gluten-Free'],
    servings: 2,
    prepTime: 15,
    cookTime: 10,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    ingredients: [
      { name: 'Shrimp', quantity: 300, unit: 'grams', calories: 200, protein: 38, carbs: 2, fat: 3 },
      { name: 'Corn tortillas', quantity: 4, unit: 'whole', calories: 200, protein: 4, carbs: 40, fat: 2 },
      { name: 'Cabbage', quantity: 100, unit: 'grams', calories: 25, protein: 1, carbs: 6, fat: 0 },
      { name: 'Sour cream', quantity: 60, unit: 'grams', calories: 120, protein: 1, carbs: 2, fat: 12 },
    ],
    steps: ['Season shrimp with cumin, paprika and lime.', 'Cook shrimp in hot pan for 2 minutes each side.', 'Warm tortillas in a dry pan.', 'Assemble tacos with shrimp, slaw and crema.'],
    totalNutrition: { calories: 545, protein: 44, carbs: 50, fat: 17 },
    perServing: { calories: 273, protein: 22, carbs: 25, fat: 9 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Hummus and Veggie Platter',
    description: 'Creamy homemade hummus served with fresh cut vegetables.',
    category: 'Snack',
    cuisine: 'Middle Eastern',
    dietaryTags: ['Vegan', 'Vegetarian', 'Gluten-Free'],
    servings: 4,
    prepTime: 10,
    cookTime: 0,
    image: 'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=800',
    ingredients: [
      { name: 'Chickpeas', quantity: 400, unit: 'grams', calories: 360, protein: 20, carbs: 60, fat: 6 },
      { name: 'Tahini', quantity: 60, unit: 'grams', calories: 180, protein: 5, carbs: 6, fat: 16 },
      { name: 'Lemon juice', quantity: 2, unit: 'tbsp', calories: 10, protein: 0, carbs: 3, fat: 0 },
      { name: 'Mixed vegetables', quantity: 300, unit: 'grams', calories: 75, protein: 3, carbs: 15, fat: 0 },
    ],
    steps: ['Blend chickpeas, tahini, lemon and garlic until smooth.', 'Add olive oil and season to taste.', 'Spread on a plate and drizzle with olive oil.', 'Serve with sliced carrots, cucumber and bell peppers.'],
    totalNutrition: { calories: 625, protein: 28, carbs: 84, fat: 22 },
    perServing: { calories: 156, protein: 7, carbs: 21, fat: 6 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Apple Peanut Butter Bites',
    description: 'Simple and satisfying snack with apple slices and peanut butter.',
    category: 'Snack',
    cuisine: 'American',
    dietaryTags: ['Vegan', 'Vegetarian', 'Gluten-Free'],
    servings: 1,
    prepTime: 5,
    cookTime: 0,
    image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800',
    ingredients: [
      { name: 'Apple', quantity: 1, unit: 'whole', calories: 80, protein: 0, carbs: 21, fat: 0 },
      { name: 'Peanut butter', quantity: 2, unit: 'tbsp', calories: 190, protein: 8, carbs: 6, fat: 16 },
    ],
    steps: ['Slice apple into thin rounds.', 'Spread peanut butter on each slice.', 'Sprinkle with cinnamon if desired.'],
    totalNutrition: { calories: 270, protein: 8, carbs: 27, fat: 16 },
    perServing: { calories: 270, protein: 8, carbs: 27, fat: 16 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Beef and Broccoli',
    description: 'Classic Chinese-American dish with tender beef and crisp broccoli.',
    category: 'Dinner',
    cuisine: 'Asian',
    dietaryTags: ['Gluten-Free'],
    servings: 2,
    prepTime: 15,
    cookTime: 15,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800',
    ingredients: [
      { name: 'Beef sirloin', quantity: 300, unit: 'grams', calories: 350, protein: 40, carbs: 0, fat: 20 },
      { name: 'Broccoli', quantity: 300, unit: 'grams', calories: 100, protein: 8, carbs: 20, fat: 0 },
      { name: 'Soy sauce', quantity: 3, unit: 'tbsp', calories: 30, protein: 3, carbs: 3, fat: 0 },
      { name: 'Sesame oil', quantity: 1, unit: 'tbsp', calories: 60, protein: 0, carbs: 0, fat: 7 },
    ],
    steps: ['Slice beef thinly against the grain.', 'Blanch broccoli for 2 minutes.', 'Stir fry beef on high heat for 3 minutes.', 'Add broccoli and sauce, toss and serve over rice.'],
    totalNutrition: { calories: 540, protein: 51, carbs: 23, fat: 27 },
    perServing: { calories: 270, protein: 26, carbs: 12, fat: 14 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Vegan Black Bean Tacos',
    description: 'Hearty plant-based tacos with spiced black beans and salsa.',
    category: 'Dinner',
    cuisine: 'Mexican',
    dietaryTags: ['Vegan', 'Vegetarian', 'Gluten-Free'],
    servings: 2,
    prepTime: 10,
    cookTime: 10,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    ingredients: [
      { name: 'Black beans', quantity: 400, unit: 'grams', calories: 340, protein: 22, carbs: 62, fat: 2 },
      { name: 'Corn tortillas', quantity: 4, unit: 'whole', calories: 200, protein: 4, carbs: 40, fat: 2 },
      { name: 'Salsa', quantity: 100, unit: 'grams', calories: 35, protein: 1, carbs: 8, fat: 0 },
      { name: 'Avocado', quantity: 1, unit: 'whole', calories: 160, protein: 2, carbs: 9, fat: 15 },
    ],
    steps: ['Heat black beans with cumin and chili powder.', 'Warm tortillas in a dry pan.', 'Mash avocado with lime and salt.', 'Fill tortillas with beans, salsa and avocado.'],
    totalNutrition: { calories: 735, protein: 29, carbs: 119, fat: 19 },
    perServing: { calories: 368, protein: 15, carbs: 60, fat: 10 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Cottage Cheese Bowl',
    description: 'High protein cottage cheese bowl with fruit and seeds.',
    category: 'Snack',
    cuisine: 'American',
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    servings: 1,
    prepTime: 5,
    cookTime: 0,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800',
    ingredients: [
      { name: 'Cottage cheese', quantity: 200, unit: 'grams', calories: 140, protein: 20, carbs: 6, fat: 4 },
      { name: 'Pineapple chunks', quantity: 100, unit: 'grams', calories: 50, protein: 0, carbs: 13, fat: 0 },
      { name: 'Pumpkin seeds', quantity: 20, unit: 'grams', calories: 110, protein: 5, carbs: 3, fat: 9 },
      { name: 'Honey', quantity: 1, unit: 'tsp', calories: 20, protein: 0, carbs: 6, fat: 0 },
    ],
    steps: ['Spoon cottage cheese into a bowl.', 'Top with pineapple chunks.', 'Sprinkle pumpkin seeds over the top.', 'Drizzle with honey and serve.'],
    totalNutrition: { calories: 320, protein: 25, carbs: 28, fat: 13 },
    perServing: { calories: 320, protein: 25, carbs: 28, fat: 13 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Zucchini Noodles with Pesto',
    description: 'Light and fresh zucchini noodles tossed with homemade basil pesto.',
    category: 'Lunch',
    cuisine: 'Italian',
    dietaryTags: ['Vegetarian', 'Gluten-Free', 'Keto'],
    servings: 2,
    prepTime: 15,
    cookTime: 5,
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800',
    ingredients: [
      { name: 'Zucchini', quantity: 400, unit: 'grams', calories: 60, protein: 4, carbs: 10, fat: 0 },
      { name: 'Basil pesto', quantity: 80, unit: 'grams', calories: 260, protein: 4, carbs: 4, fat: 26 },
      { name: 'Cherry tomatoes', quantity: 100, unit: 'grams', calories: 30, protein: 1, carbs: 6, fat: 0 },
      { name: 'Parmesan', quantity: 30, unit: 'grams', calories: 130, protein: 11, carbs: 1, fat: 9 },
    ],
    steps: ['Spiralize zucchini into noodles.', 'Saute zucchini noodles for 2 minutes.', 'Toss with pesto and cherry tomatoes.', 'Top with parmesan and serve immediately.'],
    totalNutrition: { calories: 480, protein: 20, carbs: 21, fat: 35 },
    perServing: { calories: 240, protein: 10, carbs: 11, fat: 18 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Thai Green Curry',
    description: 'Aromatic Thai green curry with coconut milk and vegetables.',
    category: 'Dinner',
    cuisine: 'Asian',
    dietaryTags: ['Vegan', 'Vegetarian', 'Gluten-Free'],
    servings: 4,
    prepTime: 15,
    cookTime: 25,
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
    ingredients: [
      { name: 'Coconut milk', quantity: 400, unit: 'ml', calories: 550, protein: 5, carbs: 10, fat: 57 },
      { name: 'Green curry paste', quantity: 50, unit: 'grams', calories: 60, protein: 2, carbs: 8, fat: 2 },
      { name: 'Mixed vegetables', quantity: 400, unit: 'grams', calories: 100, protein: 4, carbs: 20, fat: 0 },
      { name: 'Jasmine rice', quantity: 200, unit: 'grams', calories: 260, protein: 5, carbs: 57, fat: 0 },
    ],
    steps: ['Fry curry paste in a pan for 1 minute.', 'Add coconut milk and bring to a simmer.', 'Add vegetables and cook for 15 minutes.', 'Serve over jasmine rice.'],
    totalNutrition: { calories: 970, protein: 16, carbs: 95, fat: 59 },
    perServing: { calories: 243, protein: 4, carbs: 24, fat: 15 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Egg Muffins',
    description: 'Portable mini egg muffins with vegetables perfect for meal prep.',
    category: 'Breakfast',
    cuisine: 'American',
    dietaryTags: ['Vegetarian', 'Gluten-Free', 'Keto'],
    servings: 6,
    prepTime: 10,
    cookTime: 20,
    image: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800',
    ingredients: [
      { name: 'Eggs', quantity: 6, unit: 'whole', calories: 420, protein: 36, carbs: 2, fat: 30 },
      { name: 'Bell peppers', quantity: 100, unit: 'grams', calories: 30, protein: 1, carbs: 7, fat: 0 },
      { name: 'Cheddar cheese', quantity: 60, unit: 'grams', calories: 240, protein: 14, carbs: 1, fat: 20 },
      { name: 'Spinach', quantity: 50, unit: 'grams', calories: 12, protein: 1, carbs: 2, fat: 0 },
    ],
    steps: ['Preheat oven to 180C and grease a muffin tin.', 'Whisk eggs and season with salt and pepper.', 'Divide veggies and cheese into muffin cups.', 'Pour egg mixture over and bake 20 minutes.'],
    totalNutrition: { calories: 702, protein: 52, carbs: 12, fat: 50 },
    perServing: { calories: 117, protein: 9, carbs: 2, fat: 8 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Peanut Butter Energy Balls',
    description: 'No-bake energy balls with oats, peanut butter and chocolate chips.',
    category: 'Snack',
    cuisine: 'American',
    dietaryTags: ['Vegetarian'],
    servings: 12,
    prepTime: 15,
    cookTime: 0,
    image: 'https://images.unsplash.com/photo-1490567674331-8a8db42f4e44?w=800',
    ingredients: [
      { name: 'Rolled oats', quantity: 150, unit: 'grams', calories: 280, protein: 10, carbs: 50, fat: 5 },
      { name: 'Peanut butter', quantity: 120, unit: 'grams', calories: 720, protein: 30, carbs: 24, fat: 62 },
      { name: 'Honey', quantity: 60, unit: 'grams', calories: 180, protein: 0, carbs: 49, fat: 0 },
      { name: 'Chocolate chips', quantity: 60, unit: 'grams', calories: 280, protein: 3, carbs: 36, fat: 15 },
    ],
    steps: ['Mix oats, peanut butter, honey and chocolate chips.', 'Roll into small balls about 2cm each.', 'Place on a tray and refrigerate 30 minutes.', 'Store in the fridge for up to a week.'],
    totalNutrition: { calories: 1460, protein: 43, carbs: 159, fat: 82 },
    perServing: { calories: 122, protein: 4, carbs: 13, fat: 7 },
  },
  {
    user: libraryUserId,
    isUserCreated: false,
    title: 'Baked Cod with Vegetables',
    description: 'Light and healthy baked cod with roasted Mediterranean vegetables.',
    category: 'Dinner',
    cuisine: 'Mediterranean',
    dietaryTags: ['Gluten-Free', 'Keto'],
    servings: 2,
    prepTime: 10,
    cookTime: 25,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    ingredients: [
      { name: 'Cod fillet', quantity: 400, unit: 'grams', calories: 280, protein: 60, carbs: 0, fat: 2 },
      { name: 'Zucchini', quantity: 200, unit: 'grams', calories: 30, protein: 2, carbs: 6, fat: 0 },
      { name: 'Cherry tomatoes', quantity: 150, unit: 'grams', calories: 45, protein: 2, carbs: 9, fat: 0 },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp', calories: 120, protein: 0, carbs: 0, fat: 14 },
    ],
    steps: ['Preheat oven to 190C.', 'Place cod and vegetables in a baking dish.', 'Drizzle with olive oil, lemon and herbs.', 'Bake for 25 minutes until cod flakes easily.'],
    totalNutrition: { calories: 475, protein: 64, carbs: 15, fat: 16 },
    perServing: { calories: 238, protein: 32, carbs: 8, fat: 8 },
  },
];

async function seedLibraryRecipes() {
  await mongoose.connect(process.env.MONGO_URI);

  const result = await Recipe.bulkWrite(
    recipes.map(recipe => ({
      updateOne: {
        filter: { title: recipe.title, isUserCreated: false },
        update: {
          $setOnInsert: {
            ...recipe,
            ratings: [],
            averageRating: 0,
          },
        },
        upsert: true,
      },
    }))
  );

  console.log(`Library recipes ready. Inserted ${result.upsertedCount || 0}, existing ${recipes.length - (result.upsertedCount || 0)}.`);
  await mongoose.disconnect();
}

seedLibraryRecipes().catch(async err => {
  console.error(err);
  await mongoose.disconnect();
  process.exit(1);
});
